### ISSUE TITLE
Use cookie_directory to store the cookie in non-volotile memory

### ISSUE THREAD

**Issue by airwinb** [airwinb/iCloudLocationFetcher#20]
By default the cookie is stored /tmp, and this does not survive a reboot on the Rapi.

The init of PyiCloudService

def __init__(
        self, apple_id, password=None, cookie_directory=None, verify=True
    ):

**Comment by adgoudsmit** [comment]
This needs to be changed in both the main application as in the twostep autentication setup.

**Comment by airwinb** [comment]
Done by storing it in ~/iCloudLocationFetcher
